name: aws-api-test
on:
  workflow_dispatch: # allow workflow to be manually triggered
  repository_dispatch:
    types: [trigger-profiler]
concurrency:
  # cancel the current running workflow from the same branch, PR when a new workflow is triggered
  # when the trigger is not a PR but a push, it will use the commit sha to generate the concurrency group
  # {{ github.workflow }}: the workflow name is used to generate the concurrency group. This allows you to have more than one workflows
  # {{ github.ref_type }}: the type of Git ref object created in the repository. Can be either branch or tag
  # {{ github.event.pull_request.number}}: get PR number
  # {{ github.sha }}: full commit sha
  # credit: https://github.com/Sage-Bionetworks-Workflows/sagetasks/blob/main/.github/workflows/ci.yml
  group: >-
    ${{ github.workflow }}-${{ github.ref_type }}-
    ${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
jobs:
  Benchmarch-Latency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Activate a virtual environment
        run: |
          pip install --upgrade pip
          python3.10 -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run all benchmark tests
        env:
          SYNAPSE_AUTH_TOKEN: ${{ secrets.SYNAPSE_AUTH_TOKEN }}
          SERVICE_ACCOUNT_CREDS: ${{ secrets.SERVICE_ACCOUNT_CREDS }}
        run:
          |
          python3 APITests/manifest-storage.py
          python3 APITests/manifest-validate.py
          python3 APITests/manifest-submit.py
