name: aws-api-test

on:
  push:
    branches: ['develop']
  workflow_dispatch: # allow workflow to be manually triggered
  repository_dispatch:
    types: [trigger-profiler]

jobs:
  Benchmarch-Latency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Activate a virtual environment
        run: |
          pip install --upgrade pip
          python3.10 -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Generate manifest test
        env:
          SYNAPSE_AUTH_TOKEN: ${{ secrets.SYNAPSE_AUTH_TOKEN }}
          SERVICE_ACCOUNT_CREDS: ${{ secrets.SERVICE_ACCOUNT_CREDS }}
        run: python3 APITests/manifest-generator.py APITests/manifest-submit.py APITests/manifest-validate.py APITest/manifest-storage.py
